---
- name: Install tmux
  pacman:
    name: tmux
    state: present

- name: Install fzf
  pacman:
    name: fzf
    state: present

- name: Install bat
  pacman:
    name: bat
    state: present

- name: Install zoxide
  pacman:
    name: zoxide
    state: present

- name: Install tmux plugin manager (tpm)
  aur:
    name:
      - tmux-plugin-manager
    user: "{{ user.name }}"
  tags:
    - aur

- name: Ensure ~/.config/tmux directory exists
  file:
    path: "{{ user.home }}/.config/tmux"
    state: directory
    mode: '0755'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Symlink tmux config files to ~/.config/tmux
  file:
    src: "{{ user.home }}/{{ dotfiles.destination }}/config/tmux/{{ item }}"
    dest: "{{ user.home }}/.config/tmux/{{ item }}"
    state: link
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  loop:
    - tmux.conf
    - tmux.reset.conf

- name: Symlink tmux.conf to ~/.tmux.conf
  file:
    src: "{{ user.home }}/{{ dotfiles.destination }}/config/tmux/tmux.conf"
    dest: "{{ user.home }}/.tmux.conf"
    state: link
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
