---
- name: Install required packages
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: true
